version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: eduloom-education-mysql
    environment:
      MYSQL_ROOT_PASSWORD: eduloom_root_pass
      MYSQL_DATABASE: eduloom_education_db
      MYSQL_USER: eduloom_education_user
      MYSQL_PASSWORD: eduloom_education_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "eduloom_education_user", "-peduloom_education_pass"]
      interval: 5s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: eduloom-education-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: eduloom_education_user
      PMA_PASSWORD: eduloom_education_pass
    depends_on:
      - db

volumes:
  mysql_data:
